### PR TITLE
Added malloc return check

### PR DESCRIPTION
**Pull request by EgorWeders**
Malloc can return null if it can't get memory from os

### CODE REVIEW

**Comment by krlvm** [comment]
In this case, the program should crash immediately, it should not be tolerant of this

**Comment by EgorWeders** [comment]
> In this case, the program should crash immediately, it should not be tolerant of this

Not really,  malloc can return valid pointers on other function run. (For example if other program with huge ram impact crashed). In all cases that behavior should be processed, maybe not by false return, but exit(ERR_BAD_ALLOC).

**Comment by EgorWeders** [comment]
Broke branch by accident

**Comment by krlvm** [comment]
> > In this case, the program should crash immediately, it should not be tolerant of this
> 
> Not really, malloc can return valid pointers on other function run. (For example if other program with huge ram impact crashed). In all cases that behavior should be processed, maybe not by false return, but exit(ERR_BAD_ALLOC).

This is wrong in any case, out of memory errors are now mixed in with the others without any indication of a real problem, and at some point in time the program, when the memory ends completely, will silently stop working. Moreover, if you look closely at where you made changes, you will notice that most of the modified functions are called at startup - lack of memory during a startup should absolutely not be tolerated, no "for example if other program with huge ram impact crashed" will help, you will never go back there.

**Comment by EgorWeders** [comment]
> > > In this case, the program should crash immediately, it should not be tolerant of this
> > 
> > 
> > Not really, malloc can return valid pointers on other function run. (For example if other program with huge ram impact crashed). In all cases that behavior should be processed, maybe not by false return, but exit(ERR_BAD_ALLOC).
> 
> This is wrong in any case, out of memory errors are now mixed in with the others without any indication of a real problem, and at some point in time the program, when the memory ends completely, will silently stop working. Moreover, if you look closely at where you made changes, you will notice that most of the modified functions are called at startup - lack of memory during a startup should absolutely not be tolerated, no "for example if other program with huge ram impact crashed" will help, you will never go back there.

How about other option -  exit(ERR_BAD_ALLOC)  or any other code to indicate memory error? Cause main problem for me is not handled malloc nulls for user in runtime.

**Comment by EgorWeders** [comment]
> > > > In this case, the program should crash immediately, it should not be tolerant of this
> > > 
> > > 
> > > Not really, malloc can return valid pointers on other function run. (For example if other program with huge ram impact crashed). In all cases that behavior should be processed, maybe not by false return, but exit(ERR_BAD_ALLOC).
> > 
> > 
> > This is wrong in any case, out of memory errors are now mixed in with the others without any indication of a real problem, and at some point in time the program, when the memory ends completely, will silently stop working. Moreover, if you look closely at where you made changes, you will notice that most of the modified functions are called at startup - lack of memory during a startup should absolutely not be tolerated, no "for example if other program with huge ram impact crashed" will help, you will never go back there.
> 
> How about other option - exit(ERR_BAD_ALLOC) or any other code to indicate memory error? Cause main problem for me is not handled malloc nulls for user in runtime.

notice that i changed pr due lack of github interface using experience

**Comment by elfring** [comment]
>This is wrong in any case, out of memory errors are now mixed in with the others without any indication of a real problem, and at some point in time the program, when the memory ends completely, will silently stop working.

:thought_balloon: [Do you care for the advice “Do not dereference null pointers”](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Programming concerns")?

**Comment by krlvm** [comment]
> > This is wrong in any case, out of memory errors are now mixed in with the others without any indication of a real problem, and at some point in time the program, when the memory ends completely, will silently stop working.
> 
> 💭 [Do you care for the advice “Do not dereference null pointers”](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers)?

It is _very_ important if you write a piece of code that others will depend on, so you don't create unsolvable problems for the developers. If you write an application it is still important, and almost nothing less, but the handling of such errors needs to be more thought out in general, and not just an exit from an important procedure without any indication like proposed here, which will lead to weird behaviour from the user perspective.

**Pull request closed without merging**
