### PR TITLE
Runtime debug log (getenv way )

### PR DESCRIPTION
**Pull request by EgorWeders**
Added getenv() call in debug macro.
Checks only existence of variable.
Start with admin to use.
Add set DEBUG_GDPI=<smthg>

### CODE REVIEW

**Comment by EgorWeders** [comment]
Can cause some performance decrease due to the getenv call. Not much, but testing on huge loads is necessary.

**Comment by ValdikSS** [comment]
No-no, that isn't great.

Please make a pointer to a debug print function, and a macros which checks whether the pointer is NULL and calls the function.
The arguments parser then sets the function pointer to a debug print function if this option is enabled (or if environment variable is set, etc).

**Comment by ValdikSS** [comment]
Do we really need environment variable? This seems less convenient, given that none other options are set with envs.

**Comment by EgorWeders** [comment]
> Do we really need environment variable? This seems less convenient, given that none other options are set with envs.

I know, this is one of the options that I was able to test quickly. It's more complicated with the cmd argument, but  it needs to be passed on, and I don't really want to create a global variable for this (even as func pointer). I'll look at other ways. It would be better to cancel the pull request then.

**Pull request closed without merging**
